---
settings:
  name: ONTAP tools for VMware vSphere 9.12
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Les outils ONTAP pour VMware vSphere
    url: "/ontap-tools-vmware-vsphere-912"
    version-number: '9.12'
  - name: Les outils ONTAP pour VMware vSphere
    url: "/ontap-tools-vmware-vsphere"
    version-number: '9.13'
  - name: Les outils ONTAP pour VMware vSphere
    url: "/ontap-tools-vmware-vsphere-911"
    version-number: '9.11'
  - name: Les outils ONTAP pour VMware vSphere
    url: "/ontap-tools-vmware-vsphere-910"
    version-number: '9.10'
  - name: Les outils ONTAP pour VMware vSphere
    url: "/ontap-tools-vmware-vsphere-98"
    version-number: '9.8'
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation relative aux outils ONTAP pour VMware vSphere 9.12
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/release_notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - title: Mentions légales
    url: "/legal-notices.html"
